### ISSUE TITLE
Links aren't detected if h-breadcrumb mf2 is used on source page

### ISSUE THREAD

**Issue by dogada** [aaronpk/Telegraph#11]
For example please try to send webmentions for source url https://dogada.org/dvd/blog/known-review

It will be detected single  link. However for version of page without `h-breadcrumb`
https://dogada.org/dvd/blog/known-review?breadcrumbs=off

all links are detected.

Looks like it's same issue that was fixed in Bridgy yesterday:  https://github.com/snarfed/bridgy/issues/621

**Comment by aaronpk** [comment]
Interesting, I haven't seen anyone use h-breadcrumb as the first thing on the page before. It looks like the solution for Bridgy was to look for the first h-object of a known type. I could probably do the same here.

**Comment by aaronpk** [comment]
This discovery is actually done by the mention-client-php library so I've opened an issue there: https://github.com/indieweb/mention-client-php/issues/29
