### ISSUE TITLE
https certificate not accepted in Chrome 57

### ISSUE THREAD

**Issue by keithjgrant** [aaronpk/Telegraph#17]
Chrome 57 came out today, and it doesn’t accept the cert at https://telegraph.p3k.io. I am able to click through, but I see the red "not secure" warning in the address bar.

**Comment by aaronpk** [comment]
Thanks. Looks like Google removed the StartCom root so I'm going to have to replace the certificates. This affects all my apps running on *.p3k.io. https://security.googleblog.com/2016/10/distrusting-wosign-and-startcom.html

**Comment by aaronpk** [comment]
Fixed!
