### ISSUE TITLE
Do not show anchored self-URLs as URLs-to-ping

### ISSUE THREAD

**Issue by cweiske** [aaronpk/Telegraph#21]
When using the "find links" form on the dashboard, the "Send Webmentions" page shows links to anchors on the page itself. Those should be filtered out. This would be especially important for #13.

![2017-08-21 telegraph self-pinging](https://user-images.githubusercontent.com/59036/29506438-e6c814c2-864b-11e7-8ce1-59b5aabe8891.png)

**Comment by cweiske** [comment]
.. and today I re-encountered this issue and wanted to report a bug, only to find out that I already did a year ago.

**Comment by aaronpk** [comment]
haha sorry! only 6 months ago tho ;-)
