### ISSUE TITLE
telegraph.p3k.io does not resolve relative URLs to the endpoint correctly

### ISSUE THREAD

**Issue by sknebel** [aaronpk/Telegraph#22]
This was [fixed last year in mention-client-php](https://github.com/indieweb/mention-client-php/commit/208d422642871ee1fa98bcce9b8f1423c5c52773), is it possible that the updated mention-client was not deployed to telegraph.p3k.io?

Evidence:
https://telegraph.p3k.io/webmention/113DDutnwwJjI6uyay/details is a failed attempt to complete [webmention.rocks test #23](https://webmention.rocks/test/23) via https://www.svenknebel.de/temp/telegraph.html

**Comment by aaronpk** [comment]
You are absolutely correct! Apparently I never updated the mention-client library to 1.1.7. It's fixed now and passes that test! https://telegraph.p3k.io/webmention/11vW2fmnxg9hzjI5h1/details

**Comment by aaronpk** [comment]
Fixed in 93aa79445b8cc95dfd2e585fe8bc7c8cede2e97c
