### ISSUE TITLE
Wicked difficult to find the cog to edit site

### ISSUE THREAD

**Issue by eli-oat** [aaronpk/Telegraph#25]
The link to "edit site" isn't easy to discover. Consider showing it all the time, not just on hover. 

![screen shot 2018-01-19 at 4 10 50 pm](https://user-images.githubusercontent.com/3342274/35171882-5b0d9754-fd33-11e7-80e0-13754f92cc2d.png)

![screen shot 2018-01-19 at 4 10 46 pm](https://user-images.githubusercontent.com/3342274/35171883-5b26062c-fd33-11e7-8c24-2c770586d574.png)

**Comment by aaronpk** [comment]
Removed the hover effect in 18230363d65d9a4b216ee387ea7d34fc237b5a5e
