### ISSUE TITLE
Is superfeedr still offering the tracking capabilities?

### ISSUE THREAD

**Issue by cs224** [aaronpk/Telegraph#28]
I know that this is not really a question for telegraph, but I am trying to follow the documentation here: https://telegraph.p3k.io/superfeedr
There is no way (at least not in the GUI) to create such a tracking feed any longer, or is there?

Are there alternatives to superfeedr that I could use for the same purpose?

**Comment by aaronpk** [comment]
Yes I'm pretty sure it's still up, but you have to sign up for a separate "tracker" account, not one of the other accounts. Try this: https://superfeedr.com/tracker

**Comment by cs224** [comment]
Thank you very much! I had to use Google Incognito mode, so that the browser did not know that I was already signed up as publisher and I used a different mail address and user name to sign up. Then it worked.
